# Generated by Django 3.2.7 on 2022-06-13 13:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('molecule_handler', '0002_proteinsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureProfilerJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('p', 'pending'), ('r', 'running'), ('s', 'success'), ('f', 'failure')], default='p', max_length=1)),
                ('error', models.TextField(null=True)),
                ('error_detailed', models.TextField(null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_last_accessed', models.DateField(auto_now=True)),
                ('hash_value', models.CharField(default=None, max_length=256, null=True, unique=True)),
                ('density_file_pdb_code', models.CharField(max_length=4, null=True)),
                ('electron_density_map', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_structureprofiler_job_set', to='molecule_handler.electrondensitymap')),
                ('input_ligand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_structureprofiler_job_set', to='molecule_handler.ligand')),
                ('input_protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_structureprofiler_job_set', to='molecule_handler.protein')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StructureProfilerOutput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('output_data', models.JSONField()),
                ('parent_structureprofiler_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='structureprofiler.structureprofilerjob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='structureprofilerjob',
            name='output_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='structureprofiler.structureprofileroutput'),
        ),
    ]
