# Generated by Django 3.2.7 on 2022-08-18 09:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('molecule_handler', '0002_proteinsite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preprocessorjob',
            name='ligand_file_type',
        ),
        migrations.RemoveField(
            model_name='preprocessorjob',
            name='ligand_string',
        ),
        migrations.RemoveField(
            model_name='preprocessorjob',
            name='protein_file_type',
        ),
        migrations.RemoveField(
            model_name='preprocessorjob',
            name='protein_name',
        ),
        migrations.RemoveField(
            model_name='preprocessorjob',
            name='protein_string',
        ),
        migrations.CreateModel(
            name='PreprocessorJobData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_protein_string', models.TextField(null=True)),
                ('input_protein_file_type', models.CharField(default='pdb', max_length=3)),
                ('input_ligand_string', models.TextField(null=True)),
                ('input_ligand_file_type', models.CharField(default='sdf', max_length=3)),
                ('parent_preprocessor_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='molecule_handler.preprocessorjob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='preprocessorjob',
            name='input_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='molecule_handler.preprocessorjobdata'),
        ),
    ]
