# Generated by Django 3.2.7 on 2022-06-28 10:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoMineInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('info', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeoMineJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('p', 'pending'), ('r', 'running'), ('s', 'success'), ('f', 'failure')], default='p', max_length=1)),
                ('error', models.TextField(null=True)),
                ('error_detailed', models.TextField(null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_last_accessed', models.DateField(auto_now=True)),
                ('hash_value', models.CharField(default=None, max_length=256, null=True, unique=True)),
                ('filter_file', models.CharField(max_length=256)),
                ('geomine_result', models.JSONField(null=True)),
                ('geomine_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='geomine.geomineinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='geomineinfo',
            name='parent_geomine_job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='geomine.geominejob'),
        ),
    ]
