name: pplus
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.9.7
  - pip=21.2.4
  - django=3.2.7
  - djangorestframework=3.12.4
  - celery=5.1.2
  - redis=5.0.3
  - redis-py=3.5.3
  - requests=2.26.0
  - pip:
    - drf-spectacular==0.20.2
  - pillow=8.3.2
  - vine 5.0.0
  - psycopg2=2.9.1
  - pylint=2.10.2
  - pylint-django=2.4.2
  - coverage=5.5
