# Generated by Django 3.2.7 on 2022-05-12 07:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('molecule_handler', '0002_proteinsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoGSiteInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('info', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoGSiteJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('p', 'pending'), ('r', 'running'), ('s', 'success'), ('f', 'failure')], default='p', max_length=1)),
                ('error', models.TextField(null=True)),
                ('error_detailed', models.TextField(null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_last_accessed', models.DateField(auto_now=True)),
                ('hash_value', models.CharField(default=None, max_length=256, null=True, unique=True)),
                ('chain_id', models.CharField(default='', max_length=2)),
                ('calc_subpockets', models.BooleanField(default=False)),
                ('ligand_bias', models.BooleanField(default=False)),
                ('dogsite_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dogsite.dogsiteinfo')),
                ('input_ligand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_dogsite_job_set', to='molecule_handler.ligand')),
                ('input_protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_dogsite_job_set', to='molecule_handler.protein')),
                ('output_densities', models.ManyToManyField(related_name='parent_dogsite_job', to='molecule_handler.ElectronDensityMap')),
                ('output_pockets', models.ManyToManyField(related_name='parent_dogsite_job', to='molecule_handler.ProteinSite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dogsiteinfo',
            name='parent_dogsite_job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dogsite.dogsitejob'),
        ),
    ]
