# Generated by Django 3.2.7 on 2022-06-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogsitejob',
            name='ligand_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
