# Generated by Django 3.2.7 on 2022-05-20 09:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('molecule_handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdiaJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('p', 'pending'), ('r', 'running'), ('s', 'success'), ('f', 'failure')], default='p', max_length=1)),
                ('error', models.TextField(null=True)),
                ('error_detailed', models.TextField(null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_last_accessed', models.DateField(auto_now=True)),
                ('hash_value', models.CharField(default=None, max_length=256, null=True, unique=True)),
                ('density_file_pdb_code', models.CharField(max_length=4, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EdiaScores',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('atom_scores', models.JSONField()),
                ('structure_scores', models.JSONField()),
                ('parent_edia_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ediascorer.ediajob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ediajob',
            name='edia_scores',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ediascorer.ediascores'),
        ),
        migrations.AddField(
            model_name='ediajob',
            name='electron_density_map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_edia_job_set', to='molecule_handler.electrondensitymap'),
        ),
        migrations.AddField(
            model_name='ediajob',
            name='input_ligand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_edia_job_set', to='molecule_handler.ligand'),
        ),
        migrations.AddField(
            model_name='ediajob',
            name='input_protein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_edia_job_set', to='molecule_handler.protein'),
        ),
        migrations.AddField(
            model_name='ediajob',
            name='output_protein',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_edia_job', to='molecule_handler.protein'),
        ),
    ]
